// Files: 4, Nodes: 4, Edges: 2
// Roots: app, components, lib
// Detected: hasUI, hasTypes, hasTokens

// Generated by depmap infer on 2025-08-09T08:49:04.899Z
// Review and edit as needed. Rules are based on observed files and imports.

export default {
  roots: ["app","components","lib"],

  tagRules: [
    { test: /^components\/UI\/.+\.(t|j)sx?$/, kind: "ui" },
    { test: /^components\/(?!Tools\/).+\.(t|j)sx?$/, kind: "component" },
    { test: /^lib\/(types|component-types)\.ts$/, kind: "types" },
    { test: /^lib\/design-tokens\.ts$/, kind: "tokens" },
    { test: /index\.(t|j)s$/, addTags: ["barrel"] }
  ],

  ignorePolicyForTags: [],

  policy: {
    allow: {
  "other": [
    "ui",
    "tokens",
    "types"
  ],
  "ui": [
    "types",
    "tokens"
  ],
  "tokens": [
    "types",
    "tokens"
  ],
  "types": [
    "types",
    "tokens"
  ]
}
  },

  soften: {
    whenSourceHasTag: { barrel: ["policy"] }
  },

  exclude: ["^public/.*","^node_modules/.*","^storybook-static/.*"]
} as const;
